name: orbit_needlelift

task_name: orbit_needlelift

shape_meta: &shape_meta
  obs:
    point_cloud:
      shape: [1024, 3]
      type: point_cloud
    joint_pos:
      shape: [16]
      type: low_dim
  action:
    shape: [14]

env_runner:
  _target_: diffusion_policy_3d.env_runner.orbit_runner.OrbitRunner
  n_train: 20
  max_steps: 250
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}

dataset:
  _target_: diffusion_policy_3d.dataset.orbit_dataset.OrbitDataset
  zarr_path: /home/mas/Downloads/needle_handover_d3_2024-08-21_rel-cleaned.zarr/lift_needle_d3_2024-08-21_rel-cleaned.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
